default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: demo_partner_development

test:
  <<: *default
  database: demo_partner_test

production:
  <<: *default
  database: demo_partner_production
