# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eaeeb8e2b47eafe3fa36fc5d19e8bf4e61c0e7e05c714f67d586814e91557301be84c54538636f71d4b46379f92112ad472aee2ed883255ddfd3515afd673435
  quaderno_secret: d8bd9d9c94118dc62b7eeee735837f9a2afb616a673d121a874dce9053d335c2
  quaderno_id: f16b8c104188dc34fa87230e197dc01e2a703d0e633a28cd795e9eb97789b780
test:
  secret_key_base: fdd42e4976d39bd3138ae87ab7ebf29f02be9dbbac18b5d2a355a20ed5f7d003172a0fc26c58d6d83955db43d2c4d35142038d925f39807c6b5b5dc0990384e7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
